---

language: node_js

node_js:
  - lts/*

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-dev

cache:
  directories:
    - /tmp/liftoff

matrix:
  include:
    - env: DIST=juno

install:
  - npm install @elementaryos/houston

script:
  - houston ci
    --distribution $DIST

branches:
  only:
  - master